from html import escape


def reminder_settings_page(title: str, back_url: str, override: dict[str, object], *, occurrence_date: str = "") -> str:
    mode = str(override["mode"])
    custom = ", ".join(override["custom_timings"])
    suppressed = ", ".join(override["suppressed_timings"])
    occurrence = f'<p>Choose whether this change applies to occurrence {escape(occurrence_date)}, it and future occurrences, or the whole series.</p>' if occurrence_date else '<p>This applies to the whole record. Custom timings add to defaults; suppressed timings remove inherited defaults.</p>'
    scope = f'''<input type="hidden" name="occurrence_date" value="{escape(occurrence_date)}"><label><span>Apply to</span><select name="recurrence_scope"><option value="this">This occurrence</option><option value="following">This and future occurrences</option><option value="all">All occurrences</option></select></label>''' if occurrence_date else ""
    return f'''<section class="page-heading"><p class="eyebrow">Operational attention</p><h1>Reminder settings — {escape(title)}</h1>{occurrence}</section><section class="panel"><form class="record-form" method="post">{scope}<label><span>Reminder policy</span><select name="mode"><option value="default"{" selected" if mode == "default" else ""}>Use defaults</option><option value="custom"{" selected" if mode == "custom" else ""}>Use defaults with custom timings</option><option value="disabled"{" selected" if mode == "disabled" else ""}>Disable reminders</option></select></label><label><span>Add timings</span><input name="custom_timings" value="{escape(custom)}" placeholder="e.g. 2h, 1d"></label><label><span>Suppress inherited timings</span><input name="suppressed_timings" value="{escape(suppressed)}" placeholder="e.g. 10m"></label><p class="help-text">Use comma-separated positive timing tokens: m, h, d, w or mo.</p><div class="actions"><a class="button secondary" href="{escape(back_url)}">Cancel</a><button class="button">Save reminder settings</button></div></form></section>'''


def reminder_policy_page(title: str, back_url: str, *, configured_timings: list[str] | None, inherited_timings: list[str]) -> str:
    configured = configured_timings is not None
    timings = ", ".join(configured_timings if configured else inherited_timings)
    return f'''<section class="page-heading"><p class="eyebrow">Operational attention</p><h1>{escape(title)}</h1><p>Set the reminder timings used by this context. Restoring inheritance uses the next applicable default.</p></section><section class="panel"><form class="record-form" method="post"><label><span>Policy</span><select name="mode"><option value="custom"{" selected" if configured else ""}>Use these timings</option><option value="inherit"{" selected" if not configured else ""}>Use inherited defaults</option></select></label><label><span>Timings</span><input name="timings" value="{escape(timings)}" placeholder="e.g. 2h, 1d"{" required" if configured else ""}></label><p class="help-text">Use comma-separated positive timing tokens: m, h, d, w or mo.</p><p class="help-text">Inherited timings: {escape(", ".join(inherited_timings))}.</p><div class="actions"><a class="button secondary" href="{escape(back_url)}">Cancel</a><button class="button">Save reminder policy</button></div></form></section>'''
