"""Stable public facade for database and repository operations.

Implementations are separated by schema, entity, relationship and discovery concerns.
"""

from app.db_support import (
    utc_now,
    parse_int,
    sql_identifier,
    sql_literal,
    allowed_entity_type_sql,
)
from app.db_schema import (
    connect,
    initialise_database,
    create_schema,
    ensure_entity_columns,
    ensure_entity_type_constraint,
    create_typed_table,
    ensure_typed_columns,
    migrate_previous_field_values,
    migrate_field_value_aliases,
    create_relationship_table,
    ensure_relationship_columns,
    create_entity_history_table,
)
from app.entity_repository import (
    list_entities,
    list_all_entities,
    count_entities,
    get_entity,
    get_entity_by_id,
    create_entity,
    update_entity,
    delete_entity,
    validate_entity_values,
    normalise_form_values,
    insert_typed_row,
    update_typed_row,
    entity_matches_query,
)
from app.relationship_repository import (
    list_relationships,
    list_relationships_for_entity,
    get_relationship,
    create_relationship,
    update_relationship,
    delete_relationship,
    normalise_relationship_values,
    validate_relationship_values,
    normalise_relationship_direction,
    to_relationship_record,
)
from app.discovery_repository import (
    list_recent_entities,
    mark_entity_viewed,
    list_favourite_entities,
    set_entity_favourite,
    search_entities,
    matching_relationships_for_entity,
)

__all__ = [
    "utc_now",
    "connect",
    "initialise_database",
    "create_schema",
    "ensure_entity_columns",
    "ensure_entity_type_constraint",
    "create_typed_table",
    "ensure_typed_columns",
    "migrate_previous_field_values",
    "migrate_field_value_aliases",
    "create_relationship_table",
    "ensure_relationship_columns",
    "create_entity_history_table",
    "list_entities",
    "list_all_entities",
    "count_entities",
    "get_entity",
    "get_entity_by_id",
    "create_entity",
    "update_entity",
    "delete_entity",
    "validate_entity_values",
    "normalise_form_values",
    "insert_typed_row",
    "update_typed_row",
    "list_relationships",
    "list_relationships_for_entity",
    "get_relationship",
    "create_relationship",
    "update_relationship",
    "delete_relationship",
    "normalise_relationship_values",
    "validate_relationship_values",
    "normalise_relationship_direction",
    "to_relationship_record",
    "list_recent_entities",
    "mark_entity_viewed",
    "list_favourite_entities",
    "set_entity_favourite",
    "search_entities",
    "entity_matches_query",
    "matching_relationships_for_entity",
    "parse_int",
    "sql_identifier",
    "sql_literal",
    "allowed_entity_type_sql",
]
