"""Stable public facade for database and repository operations.

Implementations are separated by schema, entity, relationship and discovery concerns.
"""

from app.db_support import (
    utc_now,
    parse_int,
    sql_identifier,
    sql_literal,
    allowed_entity_type_sql,
)
from app.db_schema import (
    connect,
    initialise_database,
    create_schema,
    ensure_entity_columns,
    ensure_entity_type_constraint,
    create_typed_table,
    ensure_typed_columns,
    migrate_previous_field_values,
    migrate_field_value_aliases,
    create_relationship_table,
    ensure_relationship_columns,
    create_entity_history_table,
    create_journal_table,
    create_reference_data_tables,
    create_unit_tables,
)
from app.reference_data import (
    ReferenceItem,
    create_reference_item,
    get_reference_item,
    list_reference_items,
    list_entity_reference_values,
    replace_entity_reference_values,
)
from app.units import (
    Measurement,
    MeasurementUnit,
    clear_measurement,
    from_canonical,
    get_measurement,
    get_unit,
    list_units,
    set_measurement,
    to_canonical,
)
from app.journal_repository import (
    list_journal_entries,
    get_journal_entry,
    create_journal_entry,
    update_journal_entry,
    archive_journal_entry,
    delete_journal_entry,
)
from app.entity_repository import (
    list_entities,
    list_all_entities,
    count_entities,
    get_entity,
    get_entity_by_id,
    create_entity,
    update_entity,
    delete_entity,
    restore_entity,
    permanent_delete_entity,
    list_deleted_entities,
    entity_dependency_counts,
    validate_entity_values,
    normalise_form_values,
    insert_typed_row,
    update_typed_row,
    entity_matches_query,
)
from app.relationship_repository import (
    list_relationships,
    list_relationships_for_entity,
    get_relationship,
    create_relationship,
    update_relationship,
    delete_relationship,
    restore_relationship,
    list_deleted_relationships,
    normalise_relationship_values,
    validate_relationship_values,
    normalise_relationship_direction,
    to_relationship_record,
)
from app.discovery_repository import (
    list_recent_entities,
    mark_entity_viewed,
    list_favourite_entities,
    set_entity_favourite,
    search_entities,
    matching_relationships_for_entity,
)
from app.event_service import (
    EventInput,
    EventRecord,
    EventSchedule,
    EventUpdate,
    archive_event,
    cancel_event,
    create_event,
    get_event,
    list_events,
    normalise_event_input,
    reinstate_event,
    reschedule_event,
    unarchive_event,
    update_event,
    validate_stored_event,
)
from app.calendar_service import (
    CalendarInput,
    CalendarRecord,
    archive_calendar,
    create_calendar,
    delete_calendar,
    get_calendar,
    list_calendar_history,
    list_calendars,
    rename_calendar,
    set_default_calendar,
    unarchive_calendar,
    update_calendar,
    validate_stored_calendar,
)
from app.task_service import (
    TaskInput, TaskListInput, TaskListRecord, TaskRecord,
    archive_task, archive_task_list, complete_task, create_task, create_task_list,
    get_task, get_task_list, list_task_lists, list_tasks, reopen_task,
    rename_task_list, set_default_task_list, unarchive_task, unarchive_task_list,
    update_task, validate_stored_task, TaskSessionInput, TaskSessionRecord,
    add_task_session, delete_task_session, list_task_sessions,
)
from app.reminder_service import (
    InboxItem, act_on_inbox_item, evaluate_due_reminders, inbox_count,
    list_inbox_items, set_override, set_policy,
)

__all__ = [
    "utc_now",
    "connect",
    "initialise_database",
    "create_schema",
    "ensure_entity_columns",
    "ensure_entity_type_constraint",
    "create_typed_table",
    "ensure_typed_columns",
    "migrate_previous_field_values",
    "migrate_field_value_aliases",
    "create_relationship_table",
    "ensure_relationship_columns",
    "create_entity_history_table",
    "create_journal_table",
    "create_reference_data_tables",
    "ReferenceItem",
    "create_reference_item",
    "get_reference_item",
    "list_reference_items",
    "list_entity_reference_values",
    "replace_entity_reference_values",
    "create_unit_tables",
    "Measurement",
    "MeasurementUnit",
    "clear_measurement",
    "from_canonical",
    "get_measurement",
    "get_unit",
    "list_units",
    "set_measurement",
    "to_canonical",
    "list_journal_entries",
    "get_journal_entry",
    "create_journal_entry",
    "update_journal_entry",
    "archive_journal_entry",
    "delete_journal_entry",
    "list_entities",
    "list_all_entities",
    "count_entities",
    "get_entity",
    "get_entity_by_id",
    "create_entity",
    "update_entity",
    "delete_entity",
    "restore_entity",
    "permanent_delete_entity",
    "list_deleted_entities",
    "entity_dependency_counts",
    "validate_entity_values",
    "normalise_form_values",
    "insert_typed_row",
    "update_typed_row",
    "list_relationships",
    "list_relationships_for_entity",
    "get_relationship",
    "create_relationship",
    "update_relationship",
    "delete_relationship",
    "restore_relationship",
    "list_deleted_relationships",
    "normalise_relationship_values",
    "validate_relationship_values",
    "normalise_relationship_direction",
    "to_relationship_record",
    "list_recent_entities",
    "mark_entity_viewed",
    "list_favourite_entities",
    "set_entity_favourite",
    "search_entities",
    "entity_matches_query",
    "matching_relationships_for_entity",
    "EventInput",
    "EventRecord",
    "EventSchedule",
    "EventUpdate",
    "archive_event",
    "cancel_event",
    "create_event",
    "get_event",
    "list_events",
    "normalise_event_input",
    "reinstate_event",
    "reschedule_event",
    "unarchive_event",
    "update_event",
    "validate_stored_event",
    "CalendarInput",
    "CalendarRecord",
    "archive_calendar",
    "create_calendar",
    "delete_calendar",
    "get_calendar",
    "list_calendar_history",
    "list_calendars",
    "rename_calendar",
    "set_default_calendar",
    "unarchive_calendar",
    "update_calendar",
    "validate_stored_calendar",
    "TaskInput", "TaskListInput", "TaskListRecord", "TaskRecord",
    "archive_task", "archive_task_list", "complete_task", "create_task",
    "create_task_list", "get_task", "get_task_list", "list_task_lists",
    "list_tasks", "reopen_task", "rename_task_list", "set_default_task_list",
    "unarchive_task", "unarchive_task_list", "update_task",
    "validate_stored_task",
    "TaskSessionInput", "TaskSessionRecord", "add_task_session",
    "delete_task_session", "list_task_sessions",
    "InboxItem", "act_on_inbox_item", "evaluate_due_reminders", "inbox_count",
    "list_inbox_items", "set_override", "set_policy",
    "parse_int",
    "sql_identifier",
    "sql_literal",
    "allowed_entity_type_sql",
]
