from __future__ import annotations

import hashlib
import inspect

from app.db_connection import Connection, connect

from app.db_support import allowed_entity_type_sql, sql_identifier, sql_literal, utc_now
from app.entities import ENTITY_DEFINITIONS, EntityDefinition
from app.reference_data import create_reference_data_tables
from app.units import create_unit_tables


def initialise_database(database_url: str | None = None) -> None:
    with connect(database_url) as connection:
        create_schema(connection)


def create_schema(connection: Connection) -> None:
    create_schema_migration_table(connection)
    apply_schema_migrations(connection)


def create_schema_migration_table(connection: object) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS schema_migrations (
            migration_id TEXT PRIMARY KEY,
            checksum TEXT NOT NULL,
            applied_at TEXT NOT NULL
        )
        """
    )


def apply_schema_migrations(connection: object) -> None:
    connection.execute("SELECT pg_advisory_xact_lock(716492031)")
    applied = {
        row["migration_id"]: row["checksum"]
        for row in connection.execute("SELECT migration_id, checksum FROM schema_migrations")
    }
    for migration_id, migration in SCHEMA_MIGRATIONS:
        checksum = hashlib.sha256(inspect.getsource(migration).encode()).hexdigest()
        if migration_id in applied:
            if applied[migration_id] != checksum:
                raise RuntimeError(f"Applied migration changed: {migration_id}")
            continue
        migration(connection)
        connection.execute(
            "INSERT INTO schema_migrations (migration_id, checksum, applied_at) VALUES (?, ?, ?)",
            (migration_id, checksum, utc_now()),
        )


def ensure_current_schema(connection: object) -> None:
    create_entity_table(connection)
    ensure_entity_columns(connection)
    ensure_entity_type_constraint(connection)
    create_typed_entity_tables(connection)
    create_relationship_table(connection)
    create_inference_tables(connection)
    create_entity_history_table(connection)
    create_platform_tables(connection)
    create_journal_table(connection)
    create_entity_alias_table(connection)
    create_reference_data_tables(connection)
    create_unit_tables(connection)
    from app.taxonomy import create_taxonomy_tables, load_relationship_catalog
    create_taxonomy_tables(connection)
    load_relationship_catalog(connection)


def create_journal_table(connection: object) -> None:
    connection.executescript(
        """
        CREATE TABLE IF NOT EXISTS journal_entries (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entity_type TEXT NOT NULL,
            entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
            body TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            archived_at TEXT NOT NULL DEFAULT ''
        );
        CREATE INDEX IF NOT EXISTS idx_journal_entries_entity_chronology
            ON journal_entries (entity_type, entity_id, archived_at, created_at, id);
        """
    )


def create_entity_alias_table(connection: object) -> None:
    connection.executescript(
        """
        CREATE TABLE IF NOT EXISTS entity_aliases (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
            value TEXT NOT NULL,
            created_at TEXT NOT NULL,
            UNIQUE (entity_id, value)
        );
        CREATE INDEX IF NOT EXISTS idx_entity_aliases_value
            ON entity_aliases (lower(value));
        CREATE UNIQUE INDEX IF NOT EXISTS idx_entity_aliases_entity_value_ci
            ON entity_aliases (entity_id, lower(value));
        """
    )


def clean_document_domain_fields(connection: object) -> None:
    """Retained migration identifier; clean PostgreSQL installs need no legacy repair."""
    return


def create_platform_tables(connection: object) -> None:
    connection.executescript("""
        CREATE TABLE IF NOT EXISTS audit_events (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_type TEXT NOT NULL, occurred_at TEXT NOT NULL, actor TEXT NOT NULL DEFAULT 'local_user', notes TEXT NOT NULL DEFAULT '', before_json TEXT NOT NULL DEFAULT '', after_json TEXT NOT NULL DEFAULT '', provenance TEXT NOT NULL DEFAULT 'manual');
        CREATE TABLE IF NOT EXISTS audit_event_records (event_id INTEGER NOT NULL REFERENCES audit_events(id) ON DELETE CASCADE, record_kind TEXT NOT NULL, record_id INTEGER NOT NULL, PRIMARY KEY (event_id, record_kind, record_id));
        CREATE INDEX IF NOT EXISTS idx_audit_records ON audit_event_records(record_kind, record_id);
        CREATE TABLE IF NOT EXISTS provenance_metadata (record_kind TEXT NOT NULL, record_id INTEGER NOT NULL, field_name TEXT NOT NULL, provenance TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY (record_kind, record_id, field_name));
        CREATE TABLE IF NOT EXISTS data_quality_finding_state (finding_key TEXT PRIMARY KEY, status TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL);
    """)


def backfill_platform_audit_events(connection: object) -> None:
    """Seed audit visibility for canonical records created before generic audit existed."""
    for row in connection.execute("SELECT id, created_at, updated_at FROM entities ORDER BY id"):
        created = connection.execute(
            "INSERT INTO audit_events(event_type, occurred_at, actor, notes, provenance) VALUES('create', ?, 'system', 'Backfilled from canonical record timestamp', 'unknown')",
            (row["created_at"],),
        )
        connection.execute("INSERT INTO audit_event_records VALUES(?, 'entity', ?)", (created.lastrowid, row["id"]))
        updated = connection.execute(
            "INSERT INTO audit_events(event_type, occurred_at, actor, notes, provenance) VALUES('edit', ?, 'system', 'Backfilled from canonical record timestamp', 'unknown')",
            (row["updated_at"],),
        )
        connection.execute("INSERT INTO audit_event_records VALUES(?, 'entity', ?)", (updated.lastrowid, row["id"]))
    for row in connection.execute("SELECT id, source_entity_id, target_entity_id, created_at FROM relationships ORDER BY id"):
        event = connection.execute(
            "INSERT INTO audit_events(event_type, occurred_at, actor, notes, provenance) VALUES('relationship_change', ?, 'system', 'Relationship created (backfilled)', 'unknown')",
            (row["created_at"],),
        )
        references = ((event.lastrowid, "relationship", row["id"]), (event.lastrowid, "entity", row["source_entity_id"]), (event.lastrowid, "entity", row["target_entity_id"]))
        connection.executemany("INSERT INTO audit_event_records VALUES(?, ?, ?)", references)


def create_entity_history_table(connection: object) -> None:
    connection.executescript(
        """
        CREATE TABLE IF NOT EXISTS entity_edit_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entity_id INTEGER NOT NULL,
            event_type TEXT NOT NULL,
            details TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_entity_edit_history_entity
            ON entity_edit_history (entity_id, created_at);
        """
    )

def create_entity_table(connection: object) -> None:
    connection.executescript(
        f"""
        CREATE TABLE IF NOT EXISTS entities (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            type TEXT NOT NULL CHECK (type IN ({allowed_entity_type_sql()})),
            display_name TEXT NOT NULL,
            summary TEXT NOT NULL DEFAULT '',
            notes TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            last_viewed_at TEXT NOT NULL DEFAULT '',
            is_favourite INTEGER NOT NULL DEFAULT 0,
            deleted_at TEXT NOT NULL DEFAULT ''
        );

        CREATE INDEX IF NOT EXISTS idx_entities_type_name
            ON entities (type, display_name);
        """
    )


def create_typed_entity_tables(connection: object) -> None:
    for definition in ENTITY_DEFINITIONS:
        create_typed_table(connection, definition)


def ensure_entity_columns(connection: object) -> None:
    columns = {row["name"] for row in connection.execute("PRAGMA table_info(entities)")}
    if "last_viewed_at" not in columns:
        connection.execute("ALTER TABLE entities ADD COLUMN last_viewed_at TEXT NOT NULL DEFAULT ''")
    if "is_favourite" not in columns:
        connection.execute("ALTER TABLE entities ADD COLUMN is_favourite INTEGER NOT NULL DEFAULT 0")
    if "deleted_at" not in columns:
        connection.execute("ALTER TABLE entities ADD COLUMN deleted_at TEXT NOT NULL DEFAULT ''")
    connection.execute("CREATE INDEX IF NOT EXISTS idx_entities_deleted_at ON entities(deleted_at)")


def ensure_entity_type_constraint(connection: object) -> None:
    # The PostgreSQL baseline creates the complete current constraint. Future
    # changes must be explicit versioned migrations, not startup table repair.
    return


def create_typed_table(connection: object, definition: EntityDefinition) -> None:
    table = sql_identifier(definition.table)
    field_columns = ",\n            ".join(
        f"{sql_identifier(field.name)} TEXT NOT NULL DEFAULT ''"
        for field in definition.fields if field.typed_column
    )
    columns_sql = ",\n            " + field_columns if field_columns else ""
    connection.executescript(
        f"""
        CREATE TABLE IF NOT EXISTS {table} (
            entity_id INTEGER PRIMARY KEY REFERENCES entities(id) ON DELETE CASCADE{columns_sql}
        );
        """
    )


def ensure_typed_columns(connection: object, definition: EntityDefinition) -> None:
    table = sql_identifier(definition.table)
    columns = {row["name"] for row in connection.execute(f"PRAGMA table_info({table})")}
    for field in definition.fields:
        if not field.typed_column:
            continue
        if field.name not in columns:
            connection.execute(
                f"ALTER TABLE {table} ADD COLUMN {sql_identifier(field.name)} TEXT NOT NULL DEFAULT ''"
            )
            columns.add(field.name)
        migrate_previous_field_values(connection, definition, field, columns)
        migrate_field_value_aliases(connection, definition, field, columns)


def migrate_previous_field_values(
    connection: object,
    definition: EntityDefinition,
    field,
    columns: set[str],
) -> None:
    table = sql_identifier(definition.table)
    target = sql_identifier(field.name)
    for previous_name in field.previous_names:
        if previous_name not in columns:
            continue
        previous = sql_identifier(previous_name)
        connection.execute(
            f"""
            UPDATE {table}
            SET {target} = {previous}
            WHERE {target} = '' AND {previous} <> ''
            """
        )


def migrate_field_value_aliases(
    connection: object,
    definition: EntityDefinition,
    field,
    columns: set[str],
) -> None:
    if field.name not in columns:
        return
    table = sql_identifier(definition.table)
    column = sql_identifier(field.name)
    for old_value, new_value in field.value_aliases:
        connection.execute(
            f"UPDATE {table} SET {column} = ? WHERE {column} = ?",
            (new_value, old_value),
        )


def create_relationship_table(connection: object) -> None:
    connection.executescript(
        """
        CREATE TABLE IF NOT EXISTS relationships (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
            target_entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
            type TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'active',
            started_at TEXT NOT NULL DEFAULT '',
            started_at_precision TEXT NOT NULL DEFAULT 'exact',
            ended_at TEXT NOT NULL DEFAULT '',
            ended_at_precision TEXT NOT NULL DEFAULT 'exact',
            notes TEXT NOT NULL DEFAULT '',
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            record_origin TEXT NOT NULL DEFAULT 'manual',
            inference_suggestion_id BIGINT,
            provenance_json TEXT NOT NULL DEFAULT '',
            created_from_inference INTEGER NOT NULL DEFAULT 0,
            inference_evidence_status TEXT NOT NULL DEFAULT '',
            taxonomy_entry_id BIGINT,
            deleted_at TEXT NOT NULL DEFAULT '',
            CHECK (source_entity_id <> target_entity_id)
        );

        CREATE INDEX IF NOT EXISTS idx_relationships_source
            ON relationships (source_entity_id);

        CREATE INDEX IF NOT EXISTS idx_relationships_target
            ON relationships (target_entity_id);

        CREATE INDEX IF NOT EXISTS idx_relationships_type
            ON relationships (type);
        """
    )


def ensure_relationship_columns(connection: object) -> None:
    columns = {row["name"] for row in connection.execute("PRAGMA table_info(relationships)")}
    if "started_at_precision" not in columns:
        connection.execute("ALTER TABLE relationships ADD COLUMN started_at_precision TEXT NOT NULL DEFAULT 'exact'")
    if "ended_at_precision" not in columns:
        connection.execute("ALTER TABLE relationships ADD COLUMN ended_at_precision TEXT NOT NULL DEFAULT 'exact'")
    if "record_origin" not in columns:
        connection.execute("ALTER TABLE relationships ADD COLUMN record_origin TEXT NOT NULL DEFAULT 'manual'")
    if "inference_suggestion_id" not in columns:
        connection.execute("ALTER TABLE relationships ADD COLUMN inference_suggestion_id INTEGER")
    if "provenance_json" not in columns:
        connection.execute("ALTER TABLE relationships ADD COLUMN provenance_json TEXT NOT NULL DEFAULT ''")
    if "created_from_inference" not in columns:
        connection.execute("ALTER TABLE relationships ADD COLUMN created_from_inference INTEGER NOT NULL DEFAULT 0")
    if "inference_evidence_status" not in columns:
        connection.execute("ALTER TABLE relationships ADD COLUMN inference_evidence_status TEXT NOT NULL DEFAULT ''")
    if "deleted_at" not in columns:
        connection.execute("ALTER TABLE relationships ADD COLUMN deleted_at TEXT NOT NULL DEFAULT ''")
    connection.execute("CREATE INDEX IF NOT EXISTS idx_relationships_deleted_at ON relationships(deleted_at)")
    # Confirmed suggestions are ordinary user-owned relationships. Migrate rows
    # created under the earlier read-only origin model without losing provenance.
    connection.execute("""UPDATE relationships
        SET created_from_inference=1, record_origin='manual',
            inference_evidence_status=CASE WHEN inference_evidence_status='' THEN 'current' ELSE inference_evidence_status END
        WHERE record_origin='inferred' OR inference_suggestion_id IS NOT NULL""")


def create_inference_tables(connection: object) -> None:
    connection.executescript(
        """
        CREATE TABLE IF NOT EXISTS inference_batches (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trigger_type TEXT NOT NULL,
            trigger_id INTEGER, status TEXT NOT NULL DEFAULT 'open',
            created_at TEXT NOT NULL, dismissed_at TEXT NOT NULL DEFAULT ''
        );
        CREATE TABLE IF NOT EXISTS inference_suggestions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            batch_id INTEGER NOT NULL REFERENCES inference_batches(id) ON DELETE CASCADE,
            type TEXT NOT NULL,
            source_entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
            target_entity_id INTEGER NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
            started_at TEXT NOT NULL DEFAULT '', started_at_precision TEXT NOT NULL DEFAULT 'exact',
            status TEXT NOT NULL DEFAULT 'pending', source_type TEXT NOT NULL DEFAULT 'deterministic_rule',
            rule_key TEXT NOT NULL, supporting_relationship_ids TEXT NOT NULL,
            evidence_fingerprint TEXT NOT NULL, created_at TEXT NOT NULL,
            reviewed_at TEXT NOT NULL DEFAULT '',
            CHECK (source_entity_id <> target_entity_id)
        );
        CREATE INDEX IF NOT EXISTS idx_inference_suggestions_status ON inference_suggestions(status, batch_id);
        CREATE INDEX IF NOT EXISTS idx_inference_suggestions_pair ON inference_suggestions(type, source_entity_id, target_entity_id);
        """
    )


def create_postgresql_baseline(connection) -> None:
    """Create the clean current schema; obsolete SQLite upgrade paths are excluded."""
    create_entity_table(connection)
    create_typed_entity_tables(connection)
    create_relationship_table(connection)
    create_inference_tables(connection)
    create_entity_history_table(connection)
    create_platform_tables(connection)
    create_journal_table(connection)
    create_entity_alias_table(connection)
    create_reference_data_tables(connection)
    create_unit_tables(connection)
    from app.taxonomy import create_taxonomy_tables
    create_taxonomy_tables(connection)
    connection.execute(
        "ALTER TABLE organisations ADD COLUMN organisation_type TEXT NOT NULL DEFAULT ''"
    )
    connection.execute(
        "ALTER TABLE organisations ADD COLUMN taxonomy_entry_id BIGINT REFERENCES taxonomy_entries(id)"
    )
    connection.execute(
        "ALTER TABLE relationships ADD CONSTRAINT relationships_taxonomy_entry_fk "
        "FOREIGN KEY (taxonomy_entry_id) REFERENCES taxonomy_entries(id)"
    )
    connection.execute(
        """UPDATE relationships SET taxonomy_entry_id=(
               SELECT entry.id FROM taxonomy_entries entry
               JOIN taxonomies taxonomy ON taxonomy.id=entry.taxonomy_id
               WHERE taxonomy.key='relationship_type' AND entry.key=relationships.type
           ) WHERE taxonomy_entry_id IS NULL"""
    )


SCHEMA_MIGRATIONS = (("20260705_01_postgresql_baseline", create_postgresql_baseline),)

SCHEMA_MIGRATION_IDS = tuple(migration_id for migration_id, _ in SCHEMA_MIGRATIONS)
if len(SCHEMA_MIGRATION_IDS) != len(set(SCHEMA_MIGRATION_IDS)):
    raise ValueError("Schema migration identifiers must be unique.")
