"""Generate the tracked ethnicity catalogue from the ABS ASCCEG data cube.

Usage:
    python3 tools/update_ethnicity_catalogue.py ASCCEG.xlsx

Source page:
https://www.abs.gov.au/statistics/classifications/australian-standard-classification-cultural-and-ethnic-groups-ascceg/latest-release
"""

from pathlib import Path
import re
import sys
from xml.etree import ElementTree
from zipfile import ZipFile


MAIN_NS = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
DOC_REL_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
PKG_REL_NS = "http://schemas.openxmlformats.org/package/2006/relationships"


def cell_column(reference: str) -> str:
    return "".join(character for character in reference if character.isalpha())


def shared_strings(archive: ZipFile) -> list[str]:
    root = ElementTree.fromstring(archive.read("xl/sharedStrings.xml"))
    return [
        "".join(node.text or "" for node in item.iter(f"{{{MAIN_NS}}}t"))
        for item in root.findall(f"{{{MAIN_NS}}}si")
    ]


def worksheet_path(archive: ZipFile, sheet_name: str) -> str:
    workbook = ElementTree.fromstring(archive.read("xl/workbook.xml"))
    relationship_id = next(
        sheet.attrib[f"{{{DOC_REL_NS}}}id"]
        for sheet in workbook.iter(f"{{{MAIN_NS}}}sheet")
        if sheet.attrib["name"] == sheet_name
    )
    relationships = ElementTree.fromstring(
        archive.read("xl/_rels/workbook.xml.rels")
    )
    target = next(
        relationship.attrib["Target"]
        for relationship in relationships.findall(f"{{{PKG_REL_NS}}}Relationship")
        if relationship.attrib["Id"] == relationship_id
    )
    return "xl/" + target.removeprefix("/").removeprefix("xl/")


def read_groups(source: Path) -> list[tuple[str, str]]:
    with ZipFile(source) as archive:
        strings = shared_strings(archive)
        root = ElementTree.fromstring(
            archive.read(worksheet_path(archive, "Table 1.3"))
        )
    groups = []
    for row in root.iter(f"{{{MAIN_NS}}}row"):
        values = {}
        for cell in row.findall(f"{{{MAIN_NS}}}c"):
            value_node = cell.find(f"{{{MAIN_NS}}}v")
            if value_node is None or value_node.text is None:
                continue
            value = value_node.text
            if cell.attrib.get("t") == "s":
                value = strings[int(value)]
            values[cell_column(cell.attrib["r"])] = value.strip()
        code = values.get("C", "")
        label = values.get("D", "")
        if re.fullmatch(r"\d{4}", code) and label:
            groups.append((code, label))
    return groups


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("Pass the downloaded ASCCEG 2025 xlsx path.")
    groups = read_groups(Path(sys.argv[1]))
    if len(groups) != 276:
        raise ValueError(f"Expected 276 detailed groups, found {len(groups)}.")
    rows = "\n".join(f"    ({code!r}, {label!r})," for code, label in groups)
    output = f'''"""Generated local ethnicity catalogue; do not edit manually.

Source: Australian Bureau of Statistics, ASCCEG 2025, Table 1.3
https://www.abs.gov.au/statistics/classifications/australian-standard-classification-cultural-and-ethnic-groups-ascceg/latest-release
Generated by tools/update_ethnicity_catalogue.py.
"""

ETHNICITIES = (
{rows}
)
'''
    target = Path(__file__).resolve().parents[1] / "app" / "ethnicity_catalogue.py"
    target.write_text(output, encoding="utf-8")
    print(f"Wrote {len(groups)} ethnicities to {target}")


if __name__ == "__main__":
    main()
