"""Generate the tracked local reference catalogue from an IANA registry snapshot.

Usage:
    python3 tools/update_reference_catalogue.py REGISTRY_PATH

Download the source from:
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
"""

from pathlib import Path
import sys


def parse_records(text: str) -> list[dict[str, list[str]]]:
    records = []
    for block in text.split("%%"):
        record: dict[str, list[str]] = {}
        current_key = ""
        for line in block.strip().splitlines():
            if line.startswith(" ") and current_key:
                record[current_key][-1] += line[1:]
                continue
            key, separator, value = line.partition(": ")
            if separator:
                current_key = key
                record.setdefault(key, []).append(value)
        if record:
            records.append(record)
    return records


def active_two_letter(records, record_type: str) -> list[tuple[str, str]]:
    values = []
    for record in records:
        code = record.get("Subtag", [""])[0]
        if (
            record.get("Type", [""])[0] == record_type
            and len(code) == 2
            and code.isalpha()
            and "Deprecated" not in record
            and record.get("Description", [""])[0]
                not in {"Private use", "European Union", "United Nations"}
        ):
            values.append((code.lower(), record["Description"][0]))
    return sorted(values, key=lambda item: (item[1].casefold(), item[0]))


def tuple_source(name: str, values: list[tuple[str, str]]) -> str:
    lines = [f"{name} = ("]
    lines.extend(f"    ({code!r}, {label!r})," for code, label in values)
    lines.append(")")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("Pass the downloaded IANA registry path.")
    source = Path(sys.argv[1]).read_text(encoding="utf-8")
    records = parse_records(source)
    file_date = records[0].get("File-Date", ["unknown"])[0]
    languages = active_two_letter(records, "language")
    countries = active_two_letter(records, "region")
    output = f'''"""Generated local reference catalogue; do not edit manually.

Source: IANA Language Subtag Registry, snapshot {file_date}
https://www.iana.org/assignments/language-subtag-registry/
Generated by tools/update_reference_catalogue.py.
"""

{tuple_source("LANGUAGES", languages)}

{tuple_source("COUNTRIES", countries)}
'''
    target = Path(__file__).resolve().parents[1] / "app" / "reference_catalogue.py"
    target.write_text(output, encoding="utf-8")
    print(f"Wrote {len(languages)} languages and {len(countries)} countries to {target}")


if __name__ == "__main__":
    main()
